server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

acquiring-bank.url=http://localhost:8080
acquiring-bank.connect-timeout-ms=2000
acquiring-bank.read-timeout-ms=5000

spring.jackson.deserialization.accept-float-as-int=false